(() => {
  const DB='nest_db', VERSION=2; let db, notes=[], current=null, timer=null;
  const $=id=>document.getElementById(id); const escape=v=>{const d=document.createElement('div');d.textContent=v||'';return d.innerHTML;};
  const open=()=>new Promise((resolve,reject)=>{const r=indexedDB.open(DB,VERSION);r.onerror=()=>reject(r.error);r.onsuccess=()=>{db=r.result;resolve()};r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains('notes')){const s=r.result.createObjectStore('notes',{keyPath:'id',autoIncrement:true});s.createIndex('date','date')}}});
  const all=()=>new Promise((resolve,reject)=>{const r=db.transaction('notes').objectStore('notes').getAll();r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});
  const put=note=>new Promise((resolve,reject)=>{const r=db.transaction('notes','readwrite').objectStore('notes').put(note);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});
  const remove=id=>new Promise((resolve,reject)=>{const r=db.transaction('notes','readwrite').objectStore('notes').delete(id);r.onsuccess=resolve;r.onerror=()=>reject(r.error)});
  const matches=n=>{const q=$('note-search').value.trim().toLowerCase(),cat=$('category-filter').value;return(!cat||n.category===cat)&&(!q||[n.title,n.content,n.category,(n.tags||[]).join(' ')].join(' ').toLowerCase().includes(q));};
  function render(){const filtered=notes.filter(matches).sort((a,b)=>Number(Boolean(b.pinned))-Number(Boolean(a.pinned))||new Date(b.updated||b.date)-new Date(a.updated||a.date));$('notes-list').innerHTML=filtered.length?filtered.map(n=>`<button class="note-preview ${current?.id===n.id?'active':''}" data-id="${n.id}"><div class="note-preview-title">${n.pinned?'★ ':''}${escape(n.title||'Untitled')}</div><div class="note-preview-meta">${escape(n.category||'General')} · ${new Date(n.updated||n.date).toLocaleDateString()}</div></button>`).join(''):'<p class="empty">No notes match.</p>';document.querySelectorAll('.note-preview').forEach(b=>b.onclick=async()=>{await flush();select(Number(b.dataset.id))})}
  function select(id){current=notes.find(n=>n.id===id);if(!current)return;$('empty-editor').hidden=true;$('editor-content').hidden=false;$('note-title').value=current.title||'';$('note-content').value=current.content||'';$('note-category').value=current.category||'General';$('note-tags').value=(current.tags||[]).join(', ');$('note-pinned').checked=Boolean(current.pinned);count();render();status('Saved locally')}
  function create(){current={title:'',content:'',category:'General',tags:[],pinned:false,date:new Date().toISOString()};$('empty-editor').hidden=true;$('editor-content').hidden=false;['note-title','note-content','note-tags'].forEach(id=>$(id).value='');$('note-category').value='General';$('note-pinned').checked=false;$('note-title').focus();count();status('New note — start typing')}
  function readForm(){Object.assign(current,{title:$('note-title').value.trim()||'Untitled',content:$('note-content').value,category:$('note-category').value,tags:$('note-tags').value.split(',').map(x=>x.trim()).filter(Boolean),pinned:$('note-pinned').checked,updated:new Date().toISOString()})}
  async function save(){if(!current)return;readForm();const id=await put(current);if(!current.id){current.id=id;notes.push(current)}else notes[notes.findIndex(n=>n.id===current.id)]=current;status('Saved locally');render()}
  function schedule(){status('Saving…');clearTimeout(timer);timer=setTimeout(save,500)} async function flush(){if(!current)return;clearTimeout(timer);await save()}
  function status(text){$('save-status').textContent=text} function count(){const w=$('note-content').value.trim();$('word-count').textContent=`${w?w.split(/\s+/).length:0} words`}
  ['note-title','note-content','note-category','note-tags','note-pinned'].forEach(id=>$(id).addEventListener('input',()=>{count();schedule()}));$('note-search').oninput=render;$('category-filter').onchange=render;$('new-note-btn').onclick=async()=>{await flush();create()};$('delete-btn').onclick=async()=>{if(!current||!confirm('Delete this note?'))return;if(current.id)await remove(current.id);notes=notes.filter(n=>n.id!==current.id);current=null;$('editor-content').hidden=true;$('empty-editor').hidden=false;render()};window.addEventListener('beforeunload',()=>{if(current){clearTimeout(timer);readForm();put(current)}});
  open().then(async()=>{notes=await all();render()}).catch(e=>status(`Notes unavailable: ${e.message}`));
})();
